info:
  component: Config Server

server:
  port: 9090

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///C:/Users/andre/git/spring/config/
#        native:
#          searchLocations: file:///C:/Users/andre/git/spring/config/
management:
  context_path: /admin
  